### ISSUE TITLE
Minimum is turned into maximum validator

### ISSUE THREAD

**Issue by MKL-MikaHanke** [XHAlawa/AutoFormsBuilderFilesGenerator#6]
Api like this:
``` yaml
    Test:
      type: object
      additionalProperties: false
      properties:
        someNumber:
          type: number
          minimum: 1
          example: 42
```
will produce this:
``` typescript
...
buildForm(model: Test | null = null, 
        additionalControl: { name: string, control?: AbstractControl}[] = []) {
        
        this.form = this.fb.group({
			someNumber:[ 1 , Validators.compose([ Validators.max(1) ]) ], //should be min
 
        });
...
```
(the validator is max, when it should be min)

Bug can be found here: src/Builders/PermitiveType.ts, line 24:
[validations.push(`Validators.max(${prop.minimum})`)](https://github.com/XHAlawa/AutoFormsBuilderFilesGenerator/blob/b3b6369158282da88942224759e49f017ef981b9/src/Builders/PermitiveType.ts#L24C17-L24C68)
