### ISSUE TITLE
Suggestion: Remove special characters from enum names when accessing them

### ISSUE THREAD

**Issue by MKL-MikaHanke** [XHAlawa/AutoFormsBuilderFilesGenerator#8]
### Problem
Enums values with special characters will be accessed with the special characters in them.

### Example
api (.yaml):
```yaml
components:
  schemas:
    MyEnum:
      type: string
      enum:
        - valueone
        - value-two
        - value:three
        - valuefour-
        - value+five
        - value*six
```
will be accessed like (e.g. in onOfValidator() in buildForm()):
```typescript
oneOfValidator( [ 
  MyEnum.valueone, // works
  MyEnum.value-two, // compiler error for all other
  MyEnum.value:three,
  MyEnum.valuefour-,
  MyEnum.value+five,
  MyEnum.value*six,
] )
```

### Suggested behavior
```typescript
oneOfValidator( [ 
  MyEnum.valueone,
  MyEnum.value_two,
  MyEnum.valuethree,
  MyEnum.valuefour,
  MyEnum.valuefive,
  MyEnum.valuesix,
] )
```
So basically remove all special characters, besides the hyphen. Which should be replaced with a underscore, if its not the first or last character in the name.

---

This hat my openAPI generator creates from the example api above:

```typescript
export type MyEnum = 'valueone' | 'value-two' | 'value:three' | 'valuefour-' | 'value+five' | 'value*six';

export const MyEnum = {
    valueone: 'valueone' as MyEnum,
    value_two: 'value-two' as MyEnum,
    valuethree: 'value:three' as MyEnum,
    valuefour: 'valuefour-' as MyEnum,
    valuefive: 'value+five' as MyEnum,
    valuesix: 'value*six' as MyEnum
};
```
